site_name: thangbuiq
site_author: thangbuiq
site_description: tech documentation for me and also dev like me
copyright: Copyright 2025 @thangbuiq, All rights reserved

repo_url: https://github.com/thangbuiq/docs
repo_name: thangbuiq/docs

theme:
  name: terminal
  palette: dark

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          analysis:
            follow_imports: true
          rendering:
            show_root_full_path: false

markdown_extensions:
  - toc:
      permalink: " #"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - codehilite
  - admonition
  - pymdownx.details
  - attr_list
  - tables
  - meta

extra_css:
  - assets/styles.css
  - assets/copy_code.css

extra_javascript:
  - assets/highlight.min.js
  - assets/highlight_init.js
  - assets/copy_code.js