[project]
name = "dev-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-terminal>=4.7.0",
    "mkdocstrings>=0.27.0",
    "pygments>=2.18",
    "pymdown-extensions>=10.12",
]
